name: Release

on: push

jobs:
  build_artifact:
    name: ${{ matrix.os }}/deno-${{ matrix.deno }}/${{ github.ref }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        deno:
          - "1.6.3"

    steps:
      - name: Set binary path name
        run: echo "BINARY_PATH=README.md" >> $GITHUB_ENV

      - name: Get binary path name
        run: echo ${{env.BINARY_PATH}}

      - name: Compress binary
        uses: svenstaro/upx-action@2.0.1
        with:
          file: $BINARY_PATH
